version: '3.8'
services:
  frontend:
    image: kuantelu/portfolio-website
    build:
      dockerfile: Dockerfile.prod
    container_name: frontend-prod-c
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
